### ISSUE TITLE
Use recommended standard labels in Helm charts

### ISSUE THREAD

**Issue by jakob-ed** [bakdata/streams-bootstrap#170]
So instead of the current labels ([source](https://github.com/bakdata/streams-bootstrap/blob/ac77ee46a69714d8696395c6ced7265b2af4b1ae/charts/streams-app/templates/deployment.yaml#L24-L26))
```yaml
labels:
    app: {{ template "streams-app.name" . }}
    chart: {{ template "streams-app.chart" . }}
    release: {{ .Release.Name }}
...
```

... we should use recommended labels as detailed in [Kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) and [Helm docs](https://helm.sh/docs/chart_best_practices/labels/#standard-labels):
```yaml
labels:
    app.kubernetes.io/name: {{ template "streams-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "streams-app.chart" . }}
```
